### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Mdi' not found in 

### ISSUE THREAD

**Issue by ccinoo** [giterlizzi/dokuwiki-template-bootstrap3#446]
### Description
Hello:

Before using the default template, it was normal. After installing the bootstrap 3 template and switching to the bootstrap 3 template, an error was reported as follows:

Fatal error: Uncaught Error: Class 'Mdi' not found in /www/wiki/wiki/lib/tpl/bootstrap3/tpl/menu-tools.php:62 Stack trace: #0 /www/wiki/wiki/lib/tpl/bootstrap3/tpl/navbar.php(91): include_once() #1 /www/wiki/wiki/lib/tpl/bootstrap3/main.php(45): require_once('/www/wwwroot/cc...') #2 /www/wiki/wiki/inc/actions.php(27): include('/www/wwwroot/cc...') #3 /www/wiki/wiki/doku.php(122): act_dispatch() #4 {main} thrown in /www/wiki/wiki/lib/tpl/bootstrap3/tpl/menu-tools.php on line 62
[Description of the bug or feature]

### Steps to reproduce

1. [First Step]
use dokuwiki template
2. [Second Step]
Install and switch to bootstrap 3 template

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

* [Bootstrap3 Template]
v2019-05-22
* [DokuWiki]
Release 2018-04-22 "Greebo"
* [Plugins]
acl         authldap   ckgedit move   safefnrecode  syntaxhighlighter4  usermanager
action.php  authpdo    clearhistory  extension   pagelist    saveandedit   syntax.php addnewpage  auth.php   cli.php       imageflow  info           popularity  smtp          tag   authplain  cloud         imgpaste    remote.php  styling       testing
authad      captcha    codeprettify  include    mdpage         revert      sync          tplmod
* [PHP]
PHP7.1
* [Browser]
Chrome 77.0.3865.90
### Screenshots or Logs

[Paste your logs or attach the screenshot]
Fatal error: Uncaught Error: Class 'Mdi' not found in /www/wiki/wiki/lib/tpl/bootstrap3/tpl/menu-tools.php:62 Stack trace: #0 /www/wiki/wiki/lib/tpl/bootstrap3/tpl/navbar.php(91): include_once() #1 /www/wiki/wiki/lib/tpl/bootstrap3/main.php(45): require_once('/www/wwwroot/cc...') #2 /www/wiki/wiki/inc/actions.php(27): include('/www/wwwroot/cc...') #3 /www/wiki/wiki/doku.php(122): act_dispatch() #4 {main} thrown in /www/wiki/wiki/lib/tpl/bootstrap3/tpl/menu-tools.php on line 62

[Description of the bug or feature]

### Sample page or snippet

[Paste your sample DokuWiki page or snippet using MarkDown code syntax]

**Comment by sixteeN11** [comment]
Same here
`
[Sat Dec 07 08:43:24.984811 2019] [php7:error] [pid 329] [client 127.0.0.1:56407] PHP Fatal error:  Uncaught Error: Class 'Mdi' not found in /var/www/dokuwiki/lib/tpl/bootstrap3/tpl/menu-tools.php:62\nStack trace:\n#0 /var/www/dokuwiki/lib/tpl/bootstrap3/tpl/navbar.php(91): include_once()\n#1 /var/www/dokuwiki/lib/tpl/bootstrap3/main.php(45): require_once('/var/www/dokuwi...')\n#2 /var/www/dokuwiki/inc/actions.php(27): include('/var/www/dokuwi...')\n#3 /var/www/dokuwiki/doku.php(120): act_dispatch()\n#4 {main}\n  thrown in /var/www/dokuwiki/lib/tpl/bootstrap3/tpl/menu-tools.php on line 62, referer: http://douwiki.local/doku.php?id=start&do=admin&page=extension&tab=search&q=`

**Comment by vince2bir** [comment]
Me as well. after an update : blank page and error "Class Mdi not found"

**Comment by rgleason** [comment]
Exact same problem for us on OpenCPN Manual.
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual

How can we backup to the previous bootstrap using FTP and a new file?

**Comment by vince2bir** [comment]
Just get the previous release https://github.com/giterlizzi/dokuwiki-template-bootstrap3/releases/tag/v2018-02-16 and upload it in the tpl directory.

**Comment by cgalo5758** [comment]
I also get this error:
`[09-Dec-2019 20:43:46 America/Los_Angeles] PHP Fatal error:  Uncaught Error: Class 'Mdi' not found in /opt/bitnami/apps/dokuwiki/htdocs/lib/tpl/bootstrap3/tpl/menu$
Stack trace:
#0 /opt/bitnami/apps/dokuwiki/htdocs/lib/tpl/bootstrap3/tpl/navbar.php(91): include_once()
#1 /opt/bitnami/apps/dokuwiki/htdocs/lib/tpl/bootstrap3/main.php(45): require_once('/opt/bitnami/ap...')
#2 /opt/bitnami/apps/dokuwiki/htdocs/inc/actions.php(27): include('/opt/bitnami/ap...')
#3 /opt/bitnami/apps/dokuwiki/htdocs/doku.php(120): act_dispatch()
#4 {main}
  thrown in /opt/bitnami/apps/dokuwiki/htdocs/lib/tpl/bootstrap3/tpl/menu-tools.php on line 62`

**Comment by k4s0** [comment]
same for me
![image](https://user-images.githubusercontent.com/23264574/70506841-80ff9a80-1b2b-11ea-8ebd-8c4509734712.png)

**Comment by pankostka** [comment]
Same problem.
Clean install on USB, changing only some settings. 
(CKGEdit, camelcase = Yes, useheading = always)

**Comment by giterlizzi** [comment]
Fixed this issue in last commit in master branch. Please reinstall the template again!
Sorry!

**Comment by ccinoo** [comment]
> Fixed this issue in last commit in master branch. Please reinstall the template again!
> Sorry!

Unfortunately, the following errors are still reported after the update.

`<b>Fatal error</b>:  Uncaught Error: Class 'Mdi' not found in /www/wiki/wiki/lib/tpl/bootstrap3/tpl/menu-tools.php:77
Stack trace:
#0 /www/wiki/wiki/lib/tpl/bootstrap3/tpl/navbar.php(91): include_once()
#1 /www/wiki/wiki/lib/tpl/bootstrap3/main.php(45): require_once('/www/wwwroot/cc...')
#2 /www/wiki/wiki/inc/actions.php(27): include('/www/wwwroot/cc...')
#3 /www/wiki/wiki/doku.php(122): act_dispatch()
#4 {main}
  thrown in<b>/www/wiki/wiki/lib/tpl/bootstrap3/tpl/menu-tools.php</b> on line <b>77</b><br />`

**Comment by rgleason** [comment]
vince2br  solution:

Just get the previous release https://github.com/giterlizzi/dokuwiki-template-bootstrap3/releases/tag/v2018-02-16 and upload it in the tpl directory.

Works well for us.

**Comment by giterlizzi** [comment]
@ccinoo Sorry reinstall again the theme (now work 100%).

Joseph

**Comment by cgalo5758** [comment]
> @ccinoo Sorry reinstall again the theme (now work 100%).
> 
> Joseph

Quick Q, does this "Fix PHP invalid foreach in Menu Tools " or does it just revert that fix?

**Comment by vince2bir** [comment]
Update is OK now ! Thanks !

**Comment by ccinoo** [comment]
> Fixed this issue in last commit in master branch. Please reinstall the template again!
> Sorry!

Thank you very much. 
The problem has been solved. The template is the best.

**Comment by rgleason** [comment]
In extension manager I see an undate for
 Update: New version 2019-05-22 is available.

This is not current and I am not going to update.

**Comment by giterlizzi** [comment]
@rgleason This fix are incorporated in v2019-05-22 release.

I have added a ``build`` field in ``template.info.txt`` file:

  * ``stable/yyyymmdd`` (stable release)
  * ``hotfix/yyyymmdd`` (stable+fix)
  * ``develop/yyyymmdd`` (development release)
  * ``pre-release/yyyymmdd`` (RC release)

In the next release of template you can see the template version in Administration and ``do=check`` pages:

![immagine](https://user-images.githubusercontent.com/1824717/70667149-7dc1f700-1c70-11ea-8f48-81838a30177e.png)
