### ISSUE TITLE
callout with icon

### ISSUE THREAD

**Issue by geraldraaf** [giterlizzi/dokuwiki-template-bootstrap3#466]
### Description

after last update of bootstrap3 callout with icon="true" isn't working as expected.

I have a really large document with many pictures which take's some time to be loaded, there i can see that the icon is colored while browser is still loading and if browser has finished loading the icon is black.

### Steps to reproduce

1. <callout type="danger" title="test" icon="true">callout test</callout> -> preview 

**Expected behavior:** colored danger symbol

**Actual behavior:** black danger symbol

### Versions

* [Bootstrap3 Template] 2020.04.04 and the hotfix which is posted in issue #
* [DokuWiki] greebo
* [Plugins] too many but nothing installed or updated after bootstrap3 template
* [PHP] 7.2
* [Browser] chrome and firefox

### Screenshots or Logs

**bootstrap3 version from v2019-05-22 OK**

![callout-1](https://user-images.githubusercontent.com/1211289/78657497-269ffc00-78c9-11ea-88aa-8f24f444623c.jpg)

**bootstrap3 version from v2020-04-04 and hotfix not ok**

![callout-2](https://user-images.githubusercontent.com/1211289/78657521-30296400-78c9-11ea-98c0-46cd19a474fe.jpg)

### Sample page or snippet

see screenshot

**Comment by giterlizzi** [comment]
Thanks for reporting this issue.

Fixed this regression in master branch.

Please reinstall the template again.

Joseph

**Comment by geraldraaf** [comment]
still not working correct. Icon size is ok but still not colored as in your dokumentation
Steps to reproduce

    callout test -> preview

Expected behavior: colored symbol

Actual behavior: black symbol
Versions

    [Bootstrap3 Template] 2020.04.04 master branch and Version v2019-05-22
    [DokuWiki] greebo fresh install
    [Plugins] bootstrap3 template, bootswrapper
    [PHP] 7.2
    [Browser] chrome and firefox

Screenshots or Logs

bootstrap3 version from v2019-05-22 OK
command:

  `<callout type="success" icon="true">test</callout>`


Screenshot v2019-05-22
![callout-3](https://user-images.githubusercontent.com/1211289/78722929-bd50d500-792a-11ea-83e6-f9c85fe86301.jpg)

Screenshot v2020-04-04 after your commit icon size correct but still not colored as in v2019-05-22 and previous versions
![callout-4](https://user-images.githubusercontent.com/1211289/78723138-2e908800-792b-11ea-808a-9ea1802bea28.jpg)

I will close if you say icons are black and not colored.
